app = "exif-tool-bot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  TOKEN = "8674031134:AAFi01_IGAzuBEOrVAXrt3E1qqDpamyQZXg"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
