name: exif-tool-bot
services:
  - name: bot
    type: web
    run: python bot.py
    regions:
      - fra
    env:
      - TOKEN: secret:TOKEN
    build:
      type: docker
      dockerfile: Dockerfile
